name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write       # for creating GitHub releases and pushing version bumps
  id-token: write       # required for npm provenance
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # fetch all history for tags

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Determine version bump type
        id: version-type
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
            echo "Version bump: major"
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
            echo "Version bump: minor"
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
            echo "Version bump: patch (default)"
          fi

      - name: Bump version
        id: version-bump
        run: |
          BUMP_TYPE="${{ steps.version-type.outputs.bump }}"
          npm version $BUMP_TYPE --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version to $NEW_VERSION"

      - name: Commit and push version bump
        run: |
          git add package.json
          git commit -m "Bump version to ${{ steps.version-bump.outputs.version }} [skip ci]"
          git tag "${{ steps.version-bump.outputs.tag }}"
          git push origin main
          git push origin "${{ steps.version-bump.outputs.tag }}"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npm publish

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version-bump.outputs.tag }}
          release_name: Release ${{ steps.version-bump.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Release version ${{ steps.version-bump.outputs.version }}
            
            Built from commit ${{ github.sha }}
            Version bump type: ${{ steps.version-type.outputs.bump }}